Add docker-compose for dummy model
heartexlabs/label-studio-ml-backend pull request #50
Opened 2021-10-12 12:02 UTC by KonstantinKorotaev

2021-11-11 11:23 UTC, niklub requested changes

2021-11-11 11:23 UTC, niklub commented on label_studio_ml/examples/dummy_model/README.md
> +label-studio start --init new_project --ml-backends http://localhost:9090 --template image_classification
this is something outdated

2021-11-11 11:23 UTC, niklub commented on label_studio_ml/examples/dummy_model/README.md
> +class MyModel(BaseModel):
this too, pyheartex, BaseModel, etc.

2021-11-11 20:49 UTC, KonstantinKorotaev commented on label_studio_ml/examples/dummy_model/README.md
> +class MyModel(BaseModel):
Fixed

2021-11-11 20:50 UTC, KonstantinKorotaev commented on label_studio_ml/examples/dummy_model/README.md
> +label-studio start --init new_project --ml-backends http://localhost:9090 --template image_classification
Fixed

2022-03-28 21:11 UTC, makseq approved these changes

2022-03-28 21:11 UTC, merged