[fix] Delete label studio dependency in label-studio-ml
heartexlabs/label-studio-ml-backend pull request #52
Opened 2021-10-14 15:24 UTC by KonstantinKorotaev

2022-01-10 20:53 UTC, niklub requested changes

2022-01-10 20:53 UTC, niklub commented on requirements.txt
> +label-studio-tools==0.0.0.dev8
should we update here to the latest?

2022-01-10 20:53 UTC, niklub commented on label_studio_ml/model.py
> +def get_all_classes_inherited_LabelStudioMLBase(script_file):
why this one has been moved?

2022-01-10 20:53 UTC, niklub commented on label_studio_ml/model.py
> +import importlib
order

2022-01-10 20:53 UTC, niklub commented on label_studio_ml/utils.py
> +_DIR_APP_NAME = 'label-studio'
where this one is used?

2022-01-11 11:59 UTC, KonstantinKorotaev commented on requirements.txt
> +label-studio-tools==0.0.0.dev8
Fixed

2022-01-11 11:59 UTC, KonstantinKorotaev commented on label_studio_ml/utils.py
> +_DIR_APP_NAME = 'label-studio'
Obsolete, deleted

2022-01-11 12:02 UTC, KonstantinKorotaev commented on label_studio_ml/model.py
> +def get_all_classes_inherited_LabelStudioMLBase(script_file):
Refactored cycle dependency

2022-01-13 14:16 UTC, niklub approved these changes

2022-01-13 14:16 UTC, merged