Adopt for cloud run
heartexlabs/label-studio-ml-backend pull request #83
Opened 2022-01-26 14:28 UTC by farioas

2022-01-31 08:44 UTC, niklub commented
Add Readme with required prerequisites, parameters and usage example

2022-02-02 18:49 UTC, niklub requested changes

2022-02-02 18:49 UTC, niklub commented on label_studio_ml/server.py
> +def special_match(strg, search=re.compile(r'[^a-z-]').search):
this one doesn't work for all types of projects, e.g. `aqueous-cortex-307813`

2022-02-02 18:49 UTC, niklub commented on label_studio_ml/server.py
> +def special_match(strg, search=re.compile(r'[^a-z-]').search):
also please do not include object creation in default initializers

2022-02-02 18:52 UTC, niklub requested changes

2022-02-02 18:52 UTC, niklub commented on README.md
> +label-studio-ml deploy_gcp {project_name} --from={model_script}
could we support:
```
label-studio-ml deploy gcp {ml-backend-name} --gcp-project {project_name} --from={model_script}
```

2022-02-02 21:32 UTC, niklub commented on label_studio_ml/examples/simple_text_classifier/requirements.txt
> +# optional
why it's optional?

2022-02-02 21:34 UTC, niklub requested changes

2022-02-02 21:34 UTC, niklub commented on label_studio_ml/server.py
> +    project_id = os.environ.get("GCP_PROJECT")
let's make this env vars as arguments

2022-02-02 21:34 UTC, niklub commented on label_studio_ml/server.py
> +    ]), input=b"y", shell=True)
could we add some colored message at the end, instructing us to get this links, go on Project Settings -> Machine Learning page and put this link after "Add Model"?

2022-02-03 12:00 UTC, merged

2022-02-03 12:20 UTC, KonstantinKorotaev commented on README.md
> +label-studio-ml deploy_gcp {project_name} --from={model_script}
Fixed

2022-02-03 12:21 UTC, KonstantinKorotaev commented on label_studio_ml/examples/simple_text_classifier/requirements.txt
> +# optional
Fixed

2022-02-03 12:21 UTC, KonstantinKorotaev commented on label_studio_ml/server.py
> +    project_id = os.environ.get("GCP_PROJECT")
Fixed