fix: DEV-1693: Fix model extraction for ML_BACKEND_V2
heartexlabs/label-studio-ml-backend pull request #86
Opened 2022-02-10 13:06 UTC by KonstantinKorotaev

2022-02-10 13:07 UTC, niklub requested changes

2022-05-16 14:54 UTC, KonstantinKorotaev commented on label_studio_ml/model.py
> +        if not os.getenv('LABEL_STUDIO_ML_BACKEND_V2', default=True):
> default is False in 1.4.1

It's default for 1.4.0 and for 1.4.1 default is True

2022-05-31 12:23 UTC, makseq approved these changes

2022-05-31 12:23 UTC, makseq commented on label_studio_ml/model.py
> +        if not os.getenv('LABEL_STUDIO_ML_BACKEND_V2', default=True):
Please, make default is False everywhere and merge it.

2022-05-31 14:44 UTC, KonstantinKorotaev commented on label_studio_ml/model.py
> +        if not os.getenv('LABEL_STUDIO_ML_BACKEND_V2', default=True):
Fixed

2022-06-01 00:43 UTC, makseq approved these changes

2022-06-01 00:44 UTC, merged